# Generated by Django 3.0.4 on 2020-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('nombre', models.CharField(max_length=25)),
                ('contraseña', models.CharField(max_length=12)),
                ('primer_apellido', models.CharField(blank=True, max_length=25, null=True, verbose_name='primer apellido')),
                ('email', models.EmailField(max_length=25)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
