# Generated by Django 3.0.4 on 2020-03-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20200319_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_apellido', models.CharField(blank=True, max_length=25, null=True, verbose_name='segundo apellido')),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=60, null=True)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios')),
            ],
        ),
    ]
