# Generated by Django 3.0.4 on 2020-03-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='segundo apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='primer apellido'),
        ),
    ]
